# Site settings
title: "co3lho22"
description: "CTFs, and red teaming."
url: "https://your-username.github.io"
baseurl: ""

# Author info
author:
  name: "Diogo"
  bio: "CTF Player | Penetration Tester | Red Team Enthusiast"
  github: "Co3lho22"
  linkedin: "diogo-coelho-544139115/"
  twitter: "co3lho22"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections
collections:
  writeups:
    output: true
    permalink: /writeups/:title/
  projects:
    output: true
    permalink: /projects/:title/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: "writings"
  - scope:
      path: ""
      type: "writeups"
    values:
      layout: "writeup"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Syntax highlighting
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

